-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Avtorizaciya"
(
    "Avtorizaciya_id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Login" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Parol" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT avtorizaciya_pkey PRIMARY KEY ("Avtorizaciya_id")
);

CREATE TABLE IF NOT EXISTS public."Polzovateli"
(
    "Polzovatel_id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Familiya" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Imya" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Otchestvo" character varying(30) COLLATE pg_catalog."default",
    "Email" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Telefon" numeric NOT NULL,
    "Avtorizaciya_id" integer NOT NULL,
    CONSTRAINT polzovateli_pkey PRIMARY KEY ("Polzovatel_id"),
    CONSTRAINT polzovateli_avtorizaciya_id_key UNIQUE ("Avtorizaciya_id")
);

CREATE TABLE IF NOT EXISTS public."Dogovori_klientov"
(
    "Dogovor_klienta_id" integer NOT NULL,
    "Data_zaklucheniya" date NOT NULL,
    "Data_okonchaniya" date NOT NULL,
    "Usloviya_postavki" character varying(120) COLLATE pg_catalog."default" NOT NULL,
    "Polzovatel_id" integer NOT NULL,
    "Klient_id" integer NOT NULL,
    CONSTRAINT dogovori_klientov_pkey PRIMARY KEY ("Dogovor_klienta_id")
);

CREATE TABLE IF NOT EXISTS public."Klienti"
(
    "Klient_id" integer NOT NULL,
    "Familiya" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Imya" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Otchestvo" character varying(30) COLLATE pg_catalog."default",
    "Email" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Telefon" numeric NOT NULL,
    "Adres" character varying(120) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT klienti_pkey PRIMARY KEY ("Klient_id")
);

CREATE TABLE IF NOT EXISTS public."Zakazi_klientov"
(
    "Zakaz_klienta_id" integer NOT NULL,
    "Data_zakaza" date NOT NULL,
    "Data_otgruzki" date NOT NULL,
    "Summa" numeric NOT NULL,
    "Klient_id" integer NOT NULL,
    "Polzovatel_id" integer NOT NULL,
    "Dogovor_klienta_id" integer NOT NULL,
    "Status_id" integer NOT NULL,
    CONSTRAINT zakazi_klientov_pkey PRIMARY KEY ("Zakaz_klienta_id")
);

CREATE TABLE IF NOT EXISTS public."Status"
(
    "Status_id" integer NOT NULL,
    "Nazvanie" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT status_pkey PRIMARY KEY ("Status_id")
);

CREATE TABLE IF NOT EXISTS public."Zakazi_na_zakupku"
(
    "Zakazi_na_zakupku_id" integer NOT NULL,
    "Data_sozdaniya" date NOT NULL,
    "Ojidaemaya_data_postavki" date NOT NULL,
    "Faktichskaya_data_postavki" date,
    "Summa" numeric NOT NULL,
    "Dogovor_postavki_id" integer NOT NULL,
    "Polzovatel_id" integer NOT NULL,
    "Status_id" integer NOT NULL,
    CONSTRAINT zakazi_na_zakupku_pkey PRIMARY KEY ("Zakazi_na_zakupku_id")
);

CREATE TABLE IF NOT EXISTS public."Dogovori_postavki"
(
    "Dogovor_postavki_id" integer NOT NULL,
    "Data_zaklucheniya" date NOT NULL,
    "Data_okonchaniya" date NOT NULL,
    "Usloviya_postavki" character varying(120) COLLATE pg_catalog."default" NOT NULL,
    "Polzovatel_id" integer NOT NULL,
    "Postavshik_id" integer NOT NULL,
    CONSTRAINT dogovori_postavki_pkey PRIMARY KEY ("Dogovor_postavki_id")
);

CREATE TABLE IF NOT EXISTS public."Postavshiki"
(
    "Postavshik_id" integer NOT NULL,
    "Naimenovanie" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "INN" numeric NOT NULL,
    "Email" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Telefon" numeric NOT NULL,
    "Bank_rekvisiti" numeric NOT NULL,
    CONSTRAINT postavshiki_pkey PRIMARY KEY ("Postavshik_id")
);

CREATE TABLE IF NOT EXISTS public."Sostav_zakaza_na_zakupku"
(
    "Sostav_zakaza_na_zakupku_id" integer NOT NULL,
    "Kolichestvo_zakazano" integer NOT NULL,
    "Kolichestvo_facticheskoe" integer NOT NULL,
    "Cena_zakupki" numeric NOT NULL,
    "Summa_pozicii" numeric NOT NULL,
    "Zakazi_na_zakupku_id" integer NOT NULL,
    "Tovar_id" integer NOT NULL,
    CONSTRAINT sostav_zakaza_na_zakupku_pkey PRIMARY KEY ("Sostav_zakaza_na_zakupku_id")
);

CREATE TABLE IF NOT EXISTS public."Tovari"
(
    "Tovar_id" integer NOT NULL,
    "Naimenovanie" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Artikul" numeric NOT NULL,
    "Opisanie" character varying(300) COLLATE pg_catalog."default",
    "Proizvoditel" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Edinica_izmereniya" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Kategoriya_id" integer NOT NULL,
    "ImagePath" text COLLATE pg_catalog."default",
    CONSTRAINT tovari_pkey PRIMARY KEY ("Tovar_id")
);

CREATE TABLE IF NOT EXISTS public."Kategoriya"
(
    "Kategoriya_id" integer NOT NULL,
    "Nazvanie" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT kategoriya_pkey PRIMARY KEY ("Kategoriya_id")
);

CREATE TABLE IF NOT EXISTS public."Sostav_zakaza_klienta"
(
    "Sostav_zakaza_klienta_id" integer NOT NULL,
    "Kolichestvo_zakazano" integer NOT NULL,
    "Kolichestvo_facticheskoe" integer NOT NULL,
    "Cena" numeric NOT NULL,
    "Summa_pozicii" numeric NOT NULL,
    "Zakaz_klienta_id" integer NOT NULL,
    "Tovar_id" integer NOT NULL,
    CONSTRAINT sostav_zakaza_klienta_pkey PRIMARY KEY ("Sostav_zakaza_klienta_id")
);

CREATE TABLE IF NOT EXISTS public."Partiya_tovara"
(
    "Partiya_tovara_id" integer NOT NULL,
    "Data_proizvodstva" date NOT NULL,
    "Srok_godnosti" date NOT NULL,
    "Cena" numeric NOT NULL,
    "Cena_zakupki" numeric NOT NULL,
    "Tovar_id" integer NOT NULL,
    CONSTRAINT partiya_tovara_pkey PRIMARY KEY ("Partiya_tovara_id")
);

CREATE TABLE IF NOT EXISTS public."Ostatki"
(
    "Ostatki_id" integer NOT NULL,
    "Kolichestvo" integer NOT NULL,
    "Reserv" integer NOT NULL,
    "Partiya_tovara_id" integer NOT NULL,
    "Yachejka_hraneniya_id" integer NOT NULL,
    CONSTRAINT ostatki_pkey PRIMARY KEY ("Ostatki_id")
);

CREATE TABLE IF NOT EXISTS public."Yachejka_hraneniya"
(
    "Yachejka_hraneniya_id" integer NOT NULL,
    "Nomer_yachejki" integer NOT NULL,
    "Adres" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Sklad_id" integer NOT NULL,
    CONSTRAINT yachejka_hraneniya_pkey PRIMARY KEY ("Yachejka_hraneniya_id")
);

CREATE TABLE IF NOT EXISTS public."Skladi"
(
    "Sklad_id" integer NOT NULL,
    "Naimenovanie" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Adres" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "Polzovatel_id" integer NOT NULL,
    CONSTRAINT skladi_pkey PRIMARY KEY ("Sklad_id")
);

ALTER TABLE IF EXISTS public."Polzovateli"
    ADD CONSTRAINT polzovateli_avtorizaciya_id_fkey FOREIGN KEY ("Avtorizaciya_id")
    REFERENCES public."Avtorizaciya" ("Avtorizaciya_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS polzovateli_avtorizaciya_id_key
    ON public."Polzovateli"("Avtorizaciya_id");


ALTER TABLE IF EXISTS public."Dogovori_klientov"
    ADD CONSTRAINT dogovori_klientov_klient_id_fkey FOREIGN KEY ("Klient_id")
    REFERENCES public."Klienti" ("Klient_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Dogovori_klientov"
    ADD CONSTRAINT dogovori_klientov_polzovatel_id_fkey FOREIGN KEY ("Polzovatel_id")
    REFERENCES public."Polzovateli" ("Polzovatel_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zakazi_klientov"
    ADD CONSTRAINT zakazi_klientov_dogovor_klienta_id_fkey FOREIGN KEY ("Dogovor_klienta_id")
    REFERENCES public."Dogovori_klientov" ("Dogovor_klienta_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zakazi_klientov"
    ADD CONSTRAINT zakazi_klientov_klient_id_fkey FOREIGN KEY ("Klient_id")
    REFERENCES public."Klienti" ("Klient_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zakazi_klientov"
    ADD CONSTRAINT zakazi_klientov_polzovatel_id_fkey FOREIGN KEY ("Polzovatel_id")
    REFERENCES public."Polzovateli" ("Polzovatel_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zakazi_klientov"
    ADD CONSTRAINT zakazi_klientov_status_id_fkey FOREIGN KEY ("Status_id")
    REFERENCES public."Status" ("Status_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zakazi_na_zakupku"
    ADD CONSTRAINT zakazi_na_zakupku_dogovor_postavki_id_fkey FOREIGN KEY ("Dogovor_postavki_id")
    REFERENCES public."Dogovori_postavki" ("Dogovor_postavki_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zakazi_na_zakupku"
    ADD CONSTRAINT zakazi_na_zakupku_polzovatel_id_fkey FOREIGN KEY ("Polzovatel_id")
    REFERENCES public."Polzovateli" ("Polzovatel_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zakazi_na_zakupku"
    ADD CONSTRAINT zakazi_na_zakupku_status_id_fkey FOREIGN KEY ("Status_id")
    REFERENCES public."Status" ("Status_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Dogovori_postavki"
    ADD CONSTRAINT dogovori_postavki_polzovatel_id_fkey FOREIGN KEY ("Polzovatel_id")
    REFERENCES public."Polzovateli" ("Polzovatel_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Dogovori_postavki"
    ADD CONSTRAINT dogovori_postavki_postavshik_id_fkey FOREIGN KEY ("Postavshik_id")
    REFERENCES public."Postavshiki" ("Postavshik_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Sostav_zakaza_na_zakupku"
    ADD CONSTRAINT sostav_zakaza_na_zakupku_tovar_id_fkey FOREIGN KEY ("Tovar_id")
    REFERENCES public."Tovari" ("Tovar_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Sostav_zakaza_na_zakupku"
    ADD CONSTRAINT sostav_zakaza_na_zakupku_zakazi_na_zakupku_id_fkey FOREIGN KEY ("Zakazi_na_zakupku_id")
    REFERENCES public."Zakazi_na_zakupku" ("Zakazi_na_zakupku_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Tovari"
    ADD CONSTRAINT tovari_kategoriya_id_fkey FOREIGN KEY ("Kategoriya_id")
    REFERENCES public."Kategoriya" ("Kategoriya_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Sostav_zakaza_klienta"
    ADD CONSTRAINT sostav_zakaza_klienta_tovar_id_fkey FOREIGN KEY ("Tovar_id")
    REFERENCES public."Tovari" ("Tovar_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Sostav_zakaza_klienta"
    ADD CONSTRAINT sostav_zakaza_klienta_zakaz_klienta_id_fkey FOREIGN KEY ("Zakaz_klienta_id")
    REFERENCES public."Zakazi_klientov" ("Zakaz_klienta_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Partiya_tovara"
    ADD CONSTRAINT partiya_tovara_tovar_id_fkey FOREIGN KEY ("Tovar_id")
    REFERENCES public."Tovari" ("Tovar_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Ostatki"
    ADD CONSTRAINT ostatki_partiya_tovara_id_fkey FOREIGN KEY ("Partiya_tovara_id")
    REFERENCES public."Partiya_tovara" ("Partiya_tovara_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Ostatki"
    ADD CONSTRAINT ostatki_yachejka_hraneniya_id_fkey FOREIGN KEY ("Yachejka_hraneniya_id")
    REFERENCES public."Yachejka_hraneniya" ("Yachejka_hraneniya_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Yachejka_hraneniya"
    ADD CONSTRAINT yachejka_hraneniya_sklad_id_fkey FOREIGN KEY ("Sklad_id")
    REFERENCES public."Skladi" ("Sklad_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Skladi"
    ADD CONSTRAINT skladi_polzovatel_id_fkey FOREIGN KEY ("Polzovatel_id")
    REFERENCES public."Polzovateli" ("Polzovatel_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;